version: "3.8"
services:
  database:
    container_name: cpsportocontainer
    build:
      context: src/main/resources/init-sql
    environment:
      MYSQL_DATABASE: sls
    ports:
      - "3307:3306"